services:
  backend:
    container_name: machine-translation-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      ROOT_DIR: /app
      MODEL_ID: unsloth/gemma-3-1b-it
      PORT: 8000
      TOKENIZERS_PARALLELISM: "false"
      NVIDIA_VISIBLE_DEVICES: all
    volumes:
      - ./data:/app/data
      - ./vectorstore:/app/vectorstore
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
              